/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The DynamicLayer model module.
 * @module model/DynamicLayer
 * @version 1.0.9
 */
class DynamicLayer {
    /**
     * Constructs a new <code>DynamicLayer</code>.
     * @alias module:model/DynamicLayer
     */
    constructor() { 
        
        DynamicLayer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DynamicLayer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DynamicLayer} obj Optional instance to populate.
     * @return {module:model/DynamicLayer} The populated <code>DynamicLayer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynamicLayer();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The dynamic layer id
 * @member {String} id
 */
DynamicLayer.prototype['id'] = undefined;

/**
 * The name of the dynamic layer
 * @member {String} name
 */
DynamicLayer.prototype['name'] = undefined;

/**
 * Type of the dynamic layer. Can be 'image' or 'text'
 * @member {String} type
 */
DynamicLayer.prototype['type'] = undefined;

/**
 * The position of the dynamic layer
 * @member {Number} index
 */
DynamicLayer.prototype['index'] = undefined;






export default DynamicLayer;

