/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NewImageDynamicLayersInner from './NewImageDynamicLayersInner';

/**
 * The NewImage model module.
 * @module model/NewImage
 * @version 1.0.6
 */
class NewImage {
    /**
     * Constructs a new <code>NewImage</code>.
     * @alias module:model/NewImage
     * @param template {String} 
     */
    constructor(template) { 
        
        NewImage.initialize(this, template);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, template) { 
        obj['template'] = template;
    }

    /**
     * Constructs a <code>NewImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewImage} obj Optional instance to populate.
     * @return {module:model/NewImage} The populated <code>NewImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewImage();

            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('dynamic_layers')) {
                obj['dynamic_layers'] = ApiClient.convertToType(data['dynamic_layers'], [NewImageDynamicLayersInner]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} template
 */
NewImage.prototype['template'] = undefined;

/**
 * @member {Array.<module:model/NewImageDynamicLayersInner>} dynamic_layers
 */
NewImage.prototype['dynamic_layers'] = undefined;






export default NewImage;

