/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Template from './Template.js';

/**
 * The Templates200Response model module.
 * @module model/Templates200Response
 * @version 1.0.10
 */
class Templates200Response {
    /**
     * Constructs a new <code>Templates200Response</code>.
     * @alias module:model/Templates200Response
     */
    constructor() { 
        
        Templates200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Templates200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Templates200Response} obj Optional instance to populate.
     * @return {module:model/Templates200Response} The populated <code>Templates200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Templates200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Template]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Template>} data
 */
Templates200Response.prototype['data'] = undefined;






export default Templates200Response;

