/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient.js";
import Error from '../model/Error.js';
import NewImage from '../model/NewImage.js';
import Templates200Response from '../model/Templates200Response.js';
import ValidationError from '../model/ValidationError.js';

/**
* Mediamask service.
* @module api/MediamaskApi
* @version 1.0.8
*/
export default class MediamaskApi {

    /**
    * Constructs a new MediamaskApi. 
    * @alias module:api/MediamaskApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the html operation.
     * @callback module:api/MediamaskApi~htmlCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Render HTML for a template with dynamic layer values
     * @param {module:model/NewImage} newImage Provide the template and placeholders values that should be rendered in the image
     * @param {module:api/MediamaskApi~htmlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    html(newImage, callback) {
      let postBody = newImage;
      // verify the required parameter 'newImage' is set
      if (newImage === undefined || newImage === null) {
        throw new Error("Missing the required parameter 'newImage' when calling html");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['text/html', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/html', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the renderImage operation.
     * @callback module:api/MediamaskApi~renderImageCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Render a new image
     * @param {module:model/NewImage} newImage Provide the template and placeholders values that should be rendered in the image
     * @param {module:api/MediamaskApi~renderImageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    renderImage(newImage, callback) {
      let postBody = newImage;
      // verify the required parameter 'newImage' is set
      if (newImage === undefined || newImage === null) {
        throw new Error("Missing the required parameter 'newImage' when calling renderImage");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['image/png', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/image', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the templates operation.
     * @callback module:api/MediamaskApi~templatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Templates200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all tempaltes
     * @param {module:api/MediamaskApi~templatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Templates200Response}
     */
    templates(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Templates200Response;
      return this.apiClient.callApi(
        '/templates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
