/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Mediamask);
  }
}(this, function(expect, Mediamask) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Mediamask.Template();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Template', function() {
    it('should create an instance of Template', function() {
      // uncomment below and update the code to test Template
      //var instance = new Mediamask.Template();
      //expect(instance).to.be.a(Mediamask.Template);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property urlApi (base name: "url_api")', function() {
      // uncomment below and update the code to test the property urlApi
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property signedUrlApi (base name: "signed_url_api")', function() {
      // uncomment below and update the code to test the property signedUrlApi
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property restApi (base name: "rest_api")', function() {
      // uncomment below and update the code to test the property restApi
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

    it('should have the property dynamicLayers (base name: "dynamic_layers")', function() {
      // uncomment below and update the code to test the property dynamicLayers
      //var instance = new Mediamask.Template();
      //expect(instance).to.be();
    });

  });

}));
