/**
 * Mediamask API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Error from './model/Error';
import ImagePlaceholder from './model/ImagePlaceholder';
import NewImage from './model/NewImage';
import NewImagePlaceholdersInner from './model/NewImagePlaceholdersInner';
import TextPlaceholder from './model/TextPlaceholder';
import ValidationError from './model/ValidationError';
import ImageApi from './api/ImageApi';


/**
* Mediamask POST API Client for generating images via Javascript.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MediamaskApi = require('index'); // See note below*.
* var xxxSvc = new MediamaskApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MediamaskApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MediamaskApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MediamaskApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ImagePlaceholder model constructor.
     * @property {module:model/ImagePlaceholder}
     */
    ImagePlaceholder,

    /**
     * The NewImage model constructor.
     * @property {module:model/NewImage}
     */
    NewImage,

    /**
     * The NewImagePlaceholdersInner model constructor.
     * @property {module:model/NewImagePlaceholdersInner}
     */
    NewImagePlaceholdersInner,

    /**
     * The TextPlaceholder model constructor.
     * @property {module:model/TextPlaceholder}
     */
    TextPlaceholder,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The ImageApi service constructor.
    * @property {module:api/ImageApi}
    */
    ImageApi
};
